### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by edr17** [kbre93/every-breath-you-take#1]
Hello,

Well done. I just wanted to leave some feedback as a way to get in touch, to see if you'd be interested to work on a lightweight wearable breath tracker project which tracks the breath equally well during intensive exercise as while sitting very still? It's much smaller than the Polar H10 and doesn't involve chest straps. It tracks breathing airflow and physical movement activity. Early stage pre-seed startup.

All the best,

Ed

**Comment by kbre93** [comment]
Hi @edr17 you can contact me on kbre93@gmail.com
