### ISSUE TITLE
Error when running python EBYT.py

### ISSUE THREAD

**Issue by zain-saqer** [kbre93/every-breath-you-take#11]
Hello,
I followed the installation instructions, but I get the following message when I run `python EBYT.py`:

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: vnc, wayland, eglfs, vkkhrdisplay, minimalegl, linuxfb, xcb, offscreen, minimal, wayland-egl.

Aborted (core dumped)
```

I have Ubuntu 23.04.

What am I missing?

**Comment by hdemers** [comment]
Hi,

I had the same error and after having exported `QT_DEBUG_PLUGINS=1` and running again, I saw I was missing the library `libxcb-cursor0`. Installing it fixed the issue:
```
sudo apt install libxcb-cursor0
```
