### ISSUE TITLE
PyObjC requires macOS to build

### ISSUE THREAD

**Issue by phranger** [kbre93/every-breath-you-take#3]
Hi, attempted using windows as mentioned in the readme, however received the following error:

```
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running egg_info
      error: **PyObjC requires macOS to build**
      [end of output]
```

Can you confirm this works on windows?

**Comment by darcien** [comment]
Hi, I got the same issue on Windows.

I checked the code and didn't find any references to PyObjC directly.
So I removed the PyObjC requirements, install again, and run it.

It seems to run just fine, so maybe that's different question to the author.
What's the PyObjC used for?
![image](https://github.com/kbre93/every-breath-you-take/assets/19742419/ea272cfe-1c97-4bd1-910f-d046ec817703)

(I tested on Windows v22H2 BTW)
